// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_access_token_api_v1_login_access_token_post = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  descrption?: string | null
}

export type ItemPublic = {
  title: string
  descrption?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  descrption?: string | null
}

export type Message = {
  message: string
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type UserUpdatePasswordMe = {
  current_password: string
  new_password: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ReadItemsApiV1ItemsGetData = {
  limit?: number
  skip?: number
}

export type ReadItemsApiV1ItemsGetResponse = ItemsPublic

export type CreateItemApiV1ItemsPostData = {
  requestBody: ItemCreate
}

export type CreateItemApiV1ItemsPostResponse = ItemPublic

export type ReadItemApiV1ItemsIdGetData = {
  id: string
}

export type ReadItemApiV1ItemsIdGetResponse = ItemPublic

export type UpdateItemApiV1ItemsIdPutData = {
  id: string
  requestBody: ItemUpdate
}

export type UpdateItemApiV1ItemsIdPutResponse = ItemPublic

export type DeleteItemApiV1ItemsIdDeleteData = {
  id: string
}

export type DeleteItemApiV1ItemsIdDeleteResponse = Message

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
  formData: Body_login_access_token_api_v1_login_access_token_post
}

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = Token

export type TestTokenApiV1LoginTestTokenPostResponse = UserPublic

export type ReadUsersApiV1UsersGetData = {
  limit?: number
  skip?: number
}

export type ReadUsersApiV1UsersGetResponse = UsersPublic

export type CreateUserApiV1UsersPostData = {
  requestBody: UserCreate
}

export type CreateUserApiV1UsersPostResponse = UserPublic

export type ReadUserMeApiV1UsersMeGetResponse = UserPublic

export type DeleteUserMeApiV1UsersMeDeleteResponse = Message

export type UpdateUserMeApiV1UsersMePatchData = {
  requestBody: UserUpdateMe
}

export type UpdateUserMeApiV1UsersMePatchResponse = UserPublic

export type UpdatePasswordMeApiV1UsersMePasswordPatchData = {
  requestBody: UserUpdatePasswordMe
}

export type UpdatePasswordMeApiV1UsersMePasswordPatchResponse = Message

export type RegisterUserApiV1UsersSignupPostData = {
  requestBody: UserRegister
}

export type RegisterUserApiV1UsersSignupPostResponse = UserPublic

export type ReadUserByIdApiV1UsersUserIdGetData = {
  userId: string
}

export type ReadUserByIdApiV1UsersUserIdGetResponse = UserPublic

export type UpdateUserApiV1UsersUserIdPatchData = {
  requestBody: UserUpdate
  userId: string
}

export type UpdateUserApiV1UsersUserIdPatchResponse = UserPublic

export type DeleteUserApiV1UsersUserIdDeleteData = {
  userId: string
}

export type DeleteUserApiV1UsersUserIdDeleteResponse = Message

export type TestEmailApiV1UtilsTestEmailPostData = {
  emailTo: string
}

export type TestEmailApiV1UtilsTestEmailPostResponse = Message

export type HealthCheckApiV1UtilsHealthCheckGetResponse = boolean
